version: '2'
services:
  db:
    image: postgis/postgis:11-3.0-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  minio:
    image: minio/minio:RELEASE.2023-12-09T18-17-51Z
    ports:
      - "9000:9000"
      - "9001:9001"
    command: 'server /data --console-address ":9001"'
  minio_setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc config host add myminio http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing myminio/app
      exit 0;
      "
  server:
    build: .
    image: peakresponse/peak-server
    command: bash -l -c "npm test"
    env_file:
      - example.env
    environment:
      - CI=true
      - DATABASE_URL=postgres://postgres@db/app
      - AWS_MOBILEAPP_ACCESS_KEY_ID
      - AWS_MOBILEAPP_SECRET_ACCESS_KEY
      - AWS_S3_ACCESS_KEY_ID=minioadmin
      - AWS_S3_SECRET_ACCESS_KEY=minioadmin
      - AWS_S3_BUCKET=app
      - AWS_S3_ENDPOINT=http://minio:9000
      - AWS_S3_REGION=us-east-1
      - AWS_S3_SIGNER_ENDPOINT=http://localhost:9000
      - GOOGLE_MAPS_SERVER_API_KEY
      - NEMSIS_VALIDATOR_USERNAME
      - NEMSIS_VALIDATOR_PASSWORD
      - NEMSIS_VALIDATOR_ORGANIZATION
      - PORT=3000
    depends_on:
      - db
      - minio
      - minio_setup
