                 List of relations
 Schema |          Name          | Type  |  Owner   
--------+------------------------+-------+----------
 public | SequelizeMeta          | table | postgres
 public | agencies               | table | postgres
 public | assignments            | table | postgres
 public | cities                 | table | postgres
 public | clients                | table | postgres
 public | configurations         | table | postgres
 public | contacts               | table | postgres
 public | counties               | table | postgres
 public | custom_configurations  | table | postgres
 public | devices                | table | postgres
 public | dispatchers            | table | postgres
 public | dispatches             | table | postgres
 public | dispositions           | table | postgres
 public | employments            | table | postgres
 public | events                 | table | postgres
 public | events_agencies        | table | postgres
 public | export_logs            | table | postgres
 public | export_triggers        | table | postgres
 public | exports                | table | postgres
 public | facilities             | table | postgres
 public | files                  | table | postgres
 public | forms                  | table | postgres
 public | geography_columns      | view  | postgres
 public | geometry_columns       | view  | postgres
 public | guide_items            | table | postgres
 public | guide_sections         | table | postgres
 public | guides                 | table | postgres
 public | histories              | table | postgres
 public | incidents              | table | postgres
 public | incidents_agencies     | table | postgres
 public | interface_screens      | table | postgres
 public | interfaces             | table | postgres
 public | list_items             | table | postgres
 public | list_sections          | table | postgres
 public | lists                  | table | postgres
 public | locations              | table | postgres
 public | medications            | table | postgres
 public | narratives             | table | postgres
 public | nemsis_elements        | table | postgres
 public | nemsis_schematrons     | table | postgres
 public | nemsis_state_data_sets | table | postgres
 public | patient_observations   | table | postgres
 public | patients               | table | postgres
 public | procedures             | table | postgres
 public | psaps                  | table | postgres
 public | region_agencies        | table | postgres
 public | region_facilities      | table | postgres
 public | regions                | table | postgres
 public | reports                | table | postgres
 public | reports_files          | table | postgres
 public | reports_medications    | table | postgres
 public | reports_procedures     | table | postgres
 public | reports_signatures     | table | postgres
 public | reports_vitals         | table | postgres
 public | responders             | table | postgres
 public | responses              | table | postgres
 public | scene_observations     | table | postgres
 public | scene_pins             | table | postgres
 public | scenes                 | table | postgres
 public | screens                | table | postgres
 public | section_elements       | table | postgres
 public | sections               | table | postgres
 public | signatures             | table | postgres
 public | situations             | table | postgres
 public | spatial_ref_sys        | table | postgres
 public | states                 | table | postgres
 public | times                  | table | postgres
 public | tokens                 | table | postgres
 public | users                  | table | postgres
 public | vehicles               | table | postgres
 public | venues                 | table | postgres
 public | versions               | table | postgres
 public | vitals                 | table | postgres
(73 rows)

